<a href="https://colab.research.google.com/github/amgad2509/Brain_Tumer-detection/blob/main/Copy_of_finaaaaal_%D8%A7%D9%86_%D8%B4%D8%A7%D8%A1_%D8%A7%D9%84%D9%84%D9%87_((.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import cv2
import imutils
import numpy as np
import shutil
import matplotlib.pyplot as plt
import os
import glob
from IPython.display import Image, display
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.utils import shuffle
#from sklearn.utils import normalize

%matplotlib inline
import sklearn.model_selection
import tensorflow as tf
from tensorflow import keras
from PIL import Image
from keras.utils.np_utils import normalize
from tensorflow.keras.utils import to_categorical

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
from google.colab import drive

drive.mount('/content/drive/')

Mounted at /content/drive/


In [4]:
!unzip /content/drive/MyDrive/br.zip

Archive:  /content/drive/MyDrive/br.zip
   creating: archive/
   creating: archive/Br35H-Mask-RCNN/
  inflating: archive/Br35H-Mask-RCNN/annotations_all.json  
   creating: archive/Br35H-Mask-RCNN/TEST/
  inflating: archive/Br35H-Mask-RCNN/TEST/y710.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y791.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y768.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y718.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y793.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y795.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y707.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y799.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y728.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y722.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y770.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y732.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y757.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y702.jpg  
  inflating: archive/Br35H-Mask-RCNN/TEST/y723.jpg  
  

In [5]:
image_dirctory = '/content/archive/datasets/'

In [6]:
no_tumor_image = os.listdir(image_dirctory + 'no/')
yes_tumor_image = os.listdir(image_dirctory + 'yes/')

In [7]:
import numpy as np
dataset = []
label = []
for i, image_name in enumerate(no_tumor_image):
  if(image_name.split('.')[1] == 'jpg'):
    image = cv2.imread(image_dirctory+'no/'+image_name)
    image = Image.fromarray(image,'RGB')
    image = image.resize((64,64))
    dataset.append(np.array(image))
    label.append(0)


In [8]:
for i, image_name in enumerate(yes_tumor_image):
  if(image_name.split('.')[1] == 'jpg'):
    image = cv2.imread(image_dirctory+'yes/'+image_name)
    image = Image.fromarray(image,'RGB')
    image = image.resize((64,64))
    dataset.append(np.array(image))
    label.append(1)

In [9]:
print(len(dataset))
print(len(label))

3219
3219


In [10]:
dataset = np.array(dataset)
label = np.array(label)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_trian, y_test = train_test_split(dataset,label,test_size=0.2,random_state=0)

In [13]:
print(X_train.shape)

(2575, 64, 64, 3)


In [14]:
import tensorflow as tf
from tensorflow import keras 
from keras.utils.np_utils import normalize

In [15]:
print(X_train.shape)

(2575, 64, 64, 3)


In [16]:
X_train = normalize(X_train, axis=1)
X_test = normalize(X_test,axis=1)

y_trian = to_categorical(y_trian, num_classes=2)
y_test = to_categorical(y_test, num_classes=2)

In [17]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D,MaxPool2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.utils.np_utils import to_categorical

In [18]:

#cnn model
model=Sequential()

model.add(Conv2D(32, (3,3), input_shape=(64, 64, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(32, (3,3), kernel_initializer='he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))


model.add(Conv2D(64, (3,3), kernel_initializer='he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(2))
model.add(Activation('softmax'))
'''
[[1,2,3,4],
[4,5,6,7],
[8,9,10,11],
[8,9,10,11]]
'''

In [19]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])
model.fit(X_train, y_trian, 
batch_size=128, 
verbose=1, epochs=15, 
validation_data=(X_test, y_test),
shuffle=False)

Epoch 1/15
21/21 [==============================] - 12s 54ms/step - loss: 0.6252 - accuracy: 0.6606 - val_loss: 0.5454 - val_accuracy: 0.7469
Epoch 2/15
21/21 [==============================] - 1s 31ms/step - loss: 0.5384 - accuracy: 0.7425 - val_loss: 0.4862 - val_accuracy: 0.7686
Epoch 3/15
21/21 [==============================] - 1s 31ms/step - loss: 0.5132 - accuracy: 0.7612 - val_loss: 0.4488 - val_accuracy: 0.7950
Epoch 4/15
21/21 [==============================] - 1s 30ms/step - loss: 0.4505 - accuracy: 0.8019 - val_loss: 0.4042 - val_accuracy: 0.8307
Epoch 5/15
21/21 [==============================] - 1s 35ms/step - loss: 0.4084 - accuracy: 0.8276 - val_loss: 0.3627 - val_accuracy: 0.8416
Epoch 6/15
21/21 [==============================] - 1s 31ms/step - loss: 0.3631 - accuracy: 0.8462 - val_loss: 0.3289 - val_accuracy: 0.8463
Epoch 7/15
21/21 [==============================] - 1s 31ms/step - loss: 0.3190 - accuracy: 0.8746 - val_loss: 0.2985 - val_accuracy: 0.8618
Epoch 8/15
2

In [20]:
model.save('BrainTumorbest_model1.h5')

In [21]:
from keras.models import load_model
model=load_model('/content/BrainTumorbest_model1.h5')

In [22]:
score = model.evaluate(X_test, y_test, verbose=0)
print('\n', 'Test accuracy:', score[1]*100,"%")


 Test accuracy: 96.42857313156128 %


In [32]:
imge = cv2.imread('/content/archive/pred/pred7.jpg')
img = Image.fromarray(imge)
img = img.resize((64,64))
img = np.array(img)
print(img)

[[[ 2  2  2]
  [ 7  7  7]
  [ 9  9  9]
  ...
  [ 7  7  7]
  [ 1  1  1]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 9  9  9]
  [12 12 12]
  ...
  [ 8  8  8]
  [ 1  1  1]
  [ 0  0  0]]

 [[ 6  6  6]
  [11 11 11]
  [12 12 12]
  ...
  [11 11 11]
  [ 1  1  1]
  [ 0  0  0]]

 ...

 [[ 1  1  1]
  [ 0  0  0]
  [ 9  9  9]
  ...
  [12 12 12]
  [12 12 12]
  [12 12 12]]

 [[ 1  1  1]
  [ 0  0  0]
  [ 7  7  7]
  ...
  [12 12 12]
  [12 12 12]
  [12 12 12]]

 [[ 1  1  1]
  [ 0  0  0]
  [ 7  7  7]
  ...
  [12 12 12]
  [12 12 12]
  [12 12 12]]]


In [33]:
from keras.backend import argmax
input_img = np.expand_dims(img,axis=0)
predictions = model.predict(input_img)
classes_x=argmax(predictions,axis=1)
print(classes_x)


tf.Tensor([1], shape=(1,), dtype=int64)


In [34]:
if classes_x == 0:
  print('the MRI is NOT having a brain Tumor')
else:
  print('the MRI is having a brain Tumor')

the MRI is having a brain Tumor
